name: agent-pm
region: nyc

# Database
databases:
  - name: agentpm-db
    engine: PG
    version: "16"
    production: true
    cluster_name: agentpm-cluster

# Backend API (Flask)
services:
  - name: backend
    github:
      repo: your-username/agent-pm
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: pip install -r requirements.txt
    run_command: gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 src.web_interface:app
    http_port: 8080
    instance_count: 1
    instance_size_slug: professional-xs

    envs:
      # Flask Configuration
      - key: FLASK_ENV
        value: production
      - key: BACKEND_PORT
        value: "8080"

      # Database (auto-configured by DigitalOcean)
      - key: DATABASE_URL
        value: ${agentpm-db.DATABASE_URL}

      # JWT Secret (generate with: openssl rand -hex 32)
      - key: JWT_SECRET_KEY
        value: YOUR_JWT_SECRET_KEY_HERE
        type: SECRET

      # Google OAuth
      - key: GOOGLE_CLIENT_ID
        value: YOUR_GOOGLE_CLIENT_ID
        type: SECRET

      # Fireflies API
      - key: FIREFLIES_API_KEY
        value: YOUR_FIREFLIES_API_KEY
        type: SECRET

      # OpenAI
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
        type: SECRET

      # Jira Configuration
      - key: JIRA_URL
        value: https://your-domain.atlassian.net
      - key: JIRA_USERNAME
        value: your-email@example.com
      - key: JIRA_API_TOKEN
        value: YOUR_JIRA_API_TOKEN
        type: SECRET
      - key: JIRA_PROJECT_KEY
        value: YOUR_PROJECT

      # Slack (optional)
      - key: SLACK_BOT_TOKEN
        value: YOUR_SLACK_BOT_TOKEN
        type: SECRET
      - key: SLACK_SIGNING_SECRET
        value: YOUR_SLACK_SIGNING_SECRET
        type: SECRET
      - key: SLACK_CHANNEL
        value: "#your-channel"

      # Tempo (optional)
      - key: TEMPO_API_TOKEN
        value: YOUR_TEMPO_API_TOKEN
        type: SECRET

    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  # Frontend (React)
  - name: frontend
    github:
      repo: your-username/agent-pm
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    build_command: npm install && npm run build
    run_command: npx serve -s build -l $PORT
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs

    envs:
      - key: REACT_APP_API_URL
        value: ${backend.PUBLIC_URL}
      - key: REACT_APP_GOOGLE_CLIENT_ID
        value: YOUR_GOOGLE_CLIENT_ID
        type: SECRET

    routes:
      - path: /
