"""Add slack_installations table for OAuth flow

Revision ID: 7a2ca1bc7707
Revises: f282b6f3c49c
Create Date: 2025-11-19 12:26:42.408776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7a2ca1bc7707"
down_revision: Union[str, Sequence[str], None] = "f282b6f3c49c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("celery_tasksetmeta")
    op.drop_table("celery_taskmeta")
    op.drop_index(
        op.f("idx_meeting_prep_delivered_at"), table_name="meeting_prep_deliveries"
    )
    op.drop_index(
        op.f("idx_meeting_prep_user_project"), table_name="meeting_prep_deliveries"
    )
    op.drop_table("meeting_prep_deliveries")
    op.drop_table("slack_sessions")
    op.drop_index(op.f("idx_job_executions_recent"), table_name="job_executions")
    op.create_index(
        "idx_job_executions_recent",
        "job_executions",
        ["started_at"],
        unique=False,
        postgresql_using="btree",
        postgresql_ops={"started_at": "DESC"},
    )
    op.drop_index(
        op.f("idx_project_resource_mappings_key"),
        table_name="project_resource_mappings",
    )
    op.drop_index(op.f("idx_projects_project_work_type"), table_name="projects")
    op.drop_column("projects", "cumulative_hours")
    op.drop_column("projects", "weekly_meeting_day")
    op.drop_column("projects", "show_budget_tab")
    op.drop_column("projects", "description")
    op.drop_column("projects", "launch_date")
    op.drop_column("projects", "project_work_type")
    op.drop_column("projects", "total_hours")
    op.drop_column("projects", "send_meeting_emails")
    op.drop_column("projects", "retainer_hours")
    op.drop_column("projects", "start_date")
    op.drop_column("projects", "lead")
    op.drop_column("todo_items", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todo_items",
        sa.Column("source", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("lead", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column(
            "retainer_hours",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "send_meeting_emails",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "total_hours",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "project_work_type",
            sa.VARCHAR(length=50),
            server_default=sa.text("'project-based'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "projects",
        sa.Column("launch_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column(
            "show_budget_tab",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "weekly_meeting_day",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "cumulative_hours",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("idx_projects_project_work_type"),
        "projects",
        ["project_work_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_project_resource_mappings_key"),
        "project_resource_mappings",
        ["project_key"],
        unique=False,
    )
    op.drop_index(
        "idx_job_executions_recent",
        table_name="job_executions",
        postgresql_using="btree",
        postgresql_ops={"started_at": "DESC"},
    )
    op.create_index(
        op.f("idx_job_executions_recent"),
        "job_executions",
        [sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "slack_sessions",
        sa.Column(
            "session_id", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column("data", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("slack_sessions_pkey")),
    )
    op.create_table(
        "meeting_prep_deliveries",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "project_key", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "delivered_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "delivered_via_slack", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "delivered_via_email", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "digest_cache_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("meeting_prep_deliveries_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("meeting_prep_deliveries_pkey")),
    )
    op.create_index(
        op.f("idx_meeting_prep_user_project"),
        "meeting_prep_deliveries",
        ["user_id", "project_key"],
        unique=False,
    )
    op.create_index(
        op.f("idx_meeting_prep_delivered_at"),
        "meeting_prep_deliveries",
        ["delivered_at"],
        unique=False,
    )
    op.create_table(
        "celery_taskmeta",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "task_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True
        ),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("result", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column(
            "date_done", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("traceback", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("args", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("kwargs", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("worker", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("retries", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("queue", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("celery_taskmeta_pkey")),
        sa.UniqueConstraint(
            "task_id",
            name=op.f("celery_taskmeta_task_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "celery_tasksetmeta",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "taskset_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True
        ),
        sa.Column("result", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column(
            "date_done", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("celery_tasksetmeta_pkey")),
        sa.UniqueConstraint(
            "taskset_id",
            name=op.f("celery_tasksetmeta_taskset_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
