"""Add team tracking fields to User model: jira_account_id, team, weekly_hours_minimum

Revision ID: 87d125f604df
Revises: cbcdb0342f53
Create Date: 2025-11-08 08:11:31.004962

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87d125f604df"
down_revision: Union[str, Sequence[str], None] = "cbcdb0342f53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("jira_account_id", sa.String(length=100), nullable=True)
    )
    op.add_column("users", sa.Column("team", sa.String(length=50), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "weekly_hours_minimum", sa.Float(), nullable=False, server_default="32.0"
        ),
    )
    op.create_unique_constraint(None, "users", ["jira_account_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "weekly_hours_minimum")
    op.drop_column("users", "team")
    op.drop_column("users", "jira_account_id")
    # ### end Alembic commands ###
