"""Add project_team field to User model

Revision ID: 9e5bee700dff
Revises: 87d125f604df
Create Date: 2025-11-08 08:24:09.749207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9e5bee700dff"
down_revision: Union[str, Sequence[str], None] = "87d125f604df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables only if they exist (idempotent - these may have been dropped by cbcdb0342f53)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if "user_preferences" in existing_tables:
        op.drop_table("user_preferences")
    if "project_changes" in existing_tables:
        op.drop_table("project_changes")
    if "slack_sessions" in existing_tables:
        op.drop_table("slack_sessions")
    if "meeting_project_connections" in existing_tables:
        op.drop_table("meeting_project_connections")
    if "project_resource_mappings" in existing_tables:
        try:
            op.drop_index(
                op.f("idx_project_resource_mappings_key"),
                table_name="project_resource_mappings",
            )
        except Exception:
            pass  # Index may already be gone
        op.drop_table("project_resource_mappings")

    # Add column only if it doesn't exist
    columns = [col["name"] for col in inspector.get_columns("users")]
    if "project_team" not in columns:
        op.add_column(
            "users", sa.Column("project_team", sa.String(length=50), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "project_team")
    op.create_table(
        "project_resource_mappings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("project_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("project_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("slack_channel_ids", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("notion_page_ids", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("github_repos", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("jira_project_keys", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_resource_mappings_pkey")),
        sa.UniqueConstraint(
            "project_key",
            name=op.f("project_resource_mappings_project_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_project_resource_mappings_key"),
        "project_resource_mappings",
        ["project_key"],
        unique=False,
    )
    op.create_table(
        "meeting_project_connections",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("meeting_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("meeting_title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "meeting_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("project_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("project_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("relevance_score", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("confidence", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "matching_factors",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_confirmed_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("meeting_project_connections_pkey")),
    )
    op.create_table(
        "slack_sessions",
        sa.Column(
            "session_id", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column("data", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("slack_sessions_pkey")),
    )
    op.create_table(
        "project_changes",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("project_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("change_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ticket_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ticket_title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("old_value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("new_value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("assignee", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("reporter", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "change_timestamp",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "detected_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "change_details",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("project_changes_pkey")),
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("slack_username", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "notification_cadence", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "selected_projects",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_notification_sent",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_preferences_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("user_preferences_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
