"""Add Phase 1 PM automation tables: TimeTrackingCompliance and MonthlyReconciliationReport

Revision ID: cbcdb0342f53
Revises: 35f8455f4505
Create Date: 2025-11-08 00:45:41.264656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbcdb0342f53'
down_revision: Union[str, Sequence[str], None] = '35f8455f4505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_reconciliation_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('total_projects', sa.Integer(), nullable=False),
    sa.Column('total_epics', sa.Integer(), nullable=False),
    sa.Column('total_variance_pct', sa.Float(), nullable=True),
    sa.Column('sent_to', sa.JSON(), nullable=True),
    sa.Column('report_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_reconciliation_reports_month'), 'monthly_reconciliation_reports', ['month'], unique=True)
    op.create_table('time_tracking_compliance',
    sa.Column('user_account_id', sa.String(length=100), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('hours_logged', sa.Float(), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('pm_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_account_id', 'week_start_date')
    )
    op.create_index('idx_user_week', 'time_tracking_compliance', ['user_account_id', 'week_start_date'], unique=False)
    op.create_index('idx_week_compliance', 'time_tracking_compliance', ['week_start_date', 'is_compliant'], unique=False)
    op.drop_table('project_changes')
    op.drop_index(op.f('idx_project_resource_mappings_key'), table_name='project_resource_mappings')
    op.drop_table('project_resource_mappings')
    op.drop_table('meeting_project_connections')
    op.drop_table('slack_sessions')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_epic_hours_epic_key'), table_name='epic_hours')
    op.drop_index(op.f('ix_epic_hours_month'), table_name='epic_hours')
    op.drop_index(op.f('ix_epic_hours_project_key'), table_name='epic_hours')
    op.add_column('processed_meetings', sa.Column('ai_provider', sa.String(length=50), nullable=True))
    op.add_column('processed_meetings', sa.Column('ai_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_meetings', 'ai_model')
    op.drop_column('processed_meetings', 'ai_provider')
    op.create_index(op.f('ix_epic_hours_project_key'), 'epic_hours', ['project_key'], unique=False)
    op.create_index(op.f('ix_epic_hours_month'), 'epic_hours', ['month'], unique=False)
    op.create_index(op.f('ix_epic_hours_epic_key'), 'epic_hours', ['epic_key'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slack_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_cadence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('selected_projects', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_notification_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_preferences_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('slack_sessions',
    sa.Column('session_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('slack_sessions_pkey'))
    )
    op.create_table('meeting_project_connections',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meeting_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meeting_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meeting_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('project_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relevance_score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('matching_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('meeting_project_connections_pkey'))
    )
    op.create_table('project_resource_mappings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slack_channel_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notion_page_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('github_repos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('jira_project_keys', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('internal_slack_channels', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('project_resource_mappings_pkey')),
    sa.UniqueConstraint('project_key', name=op.f('project_resource_mappings_project_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_project_resource_mappings_key'), 'project_resource_mappings', ['project_key'], unique=False)
    op.create_table('project_changes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('change_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ticket_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ticket_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('old_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assignee', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reporter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('change_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('change_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('project_changes_pkey'))
    )
    op.drop_index('idx_week_compliance', table_name='time_tracking_compliance')
    op.drop_index('idx_user_week', table_name='time_tracking_compliance')
    op.drop_table('time_tracking_compliance')
    op.drop_index(op.f('ix_monthly_reconciliation_reports_month'), table_name='monthly_reconciliation_reports')
    op.drop_table('monthly_reconciliation_reports')
    # ### end Alembic commands ###
