"""Proactive insight model for tracking AI-generated insights and alerts."""
from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey, JSON
from sqlalchemy.orm import relationship
from datetime import datetime, timezone

from .base import Base


class ProactiveInsight(Base):
    """Model for storing proactive insights generated by the system."""
    __tablename__ = 'proactive_insights'

    id = Column(String(36), primary_key=True)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    project_key = Column(String(50), nullable=True, index=True)
    insight_type = Column(String(50), nullable=False, index=True)  # 'stale_pr', 'budget_alert', 'missing_ticket', 'anomaly', 'meeting_prep'
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    severity = Column(String(20), nullable=False)  # 'info', 'warning', 'critical'
    insight_metadata = Column(JSON, nullable=True)  # Flexible storage for type-specific data
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)
    dismissed_at = Column(DateTime, nullable=True)
    acted_on_at = Column(DateTime, nullable=True)
    action_taken = Column(String(100), nullable=True)  # 'created_ticket', 'ignored', 'resolved', etc.
    delivered_via_slack = Column(DateTime, nullable=True)  # Track when delivered via Slack
    delivered_via_email = Column(DateTime, nullable=True)  # Track when delivered via Email

    # Relationship
    user = relationship("User", backref="proactive_insights")

    def to_dict(self):
        """Convert insight to dictionary."""
        return {
            'id': self.id,
            'user_id': self.user_id,
            'project_key': self.project_key,
            'insight_type': self.insight_type,
            'title': self.title,
            'description': self.description,
            'severity': self.severity,
            'metadata': self.insight_metadata,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'dismissed_at': self.dismissed_at.isoformat() if self.dismissed_at else None,
            'acted_on_at': self.acted_on_at.isoformat() if self.acted_on_at else None,
            'action_taken': self.action_taken,
            'delivered_via_slack': self.delivered_via_slack.isoformat() if self.delivered_via_slack else None,
            'delivered_via_email': self.delivered_via_email.isoformat() if self.delivered_via_email else None,
        }

    def is_delivered(self):
        """Check if insight has been delivered to user."""
        return self.delivered_via_slack is not None or self.delivered_via_email is not None

    def is_dismissed(self):
        """Check if insight has been dismissed."""
        return self.dismissed_at is not None

    def is_acted_on(self):
        """Check if insight has been acted upon."""
        return self.acted_on_at is not None
