name: Nightly Meeting Analysis

# Runs daily at 7 AM UTC (3 AM EST) to analyze meetings from active projects
# Runs 1 hour after vector sync to ensure Fireflies meetings are available
on:
  schedule:
    - cron: '0 7 * * *'  # 7 AM UTC daily (3 AM EST)
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  analyze-meetings:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for vector sync to complete
        run: |
          echo "⏰ Waiting 30 seconds to ensure vector sync job has completed..."
          sleep 30

      - name: Trigger Meeting Analysis Sync (Celery)
        run: |
          echo "🔍 Queuing meeting analysis for active projects (3-day lookback)..."
          curl -X POST \
            -H "X-Admin-Key: ${{ secrets.ADMIN_API_KEY }}" \
            "https://agent-pm-tsbbb.ondigitalocean.app/api/scheduler/celery/meeting-analysis-sync" \
            || echo "❌ Meeting analysis sync failed"
          sleep 5

      - name: Verify Analysis Results
        run: |
          echo "📊 Checking analysis results..."
          sleep 10
          curl -s -H "X-Admin-Key: ${{ secrets.ADMIN_API_KEY }}" \
            "https://agent-pm-tsbbb.ondigitalocean.app/api/meetings" \
            || echo "❌ Analysis results check failed"
